### ISSUE TITLE
ValueError when I try to add Image Embedding

### ISSUE THREAD

**Issue by KamilBrankiewicz** [biolab/orange3-imageanalytics#33] opened 2017-04-24 09:11 UTC
Hi
I have some issue when I try to add Image Embedding. I have Orange version 3.4.2 and Image Analytics 0.1.5.

Exception:
```
ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.
Module:
orangecontrib.imageanalytics.image_embedder:137
Widget Name:
Image Embedding
Widget Module:
orangecontrib.imageanalytics.widgets.owimageembedding:114
Widget Scheme:
C:\Users\Kamil\AppData\Local\Temp\ows-xby3pcyb.ows.xml
Version:
3.4.2
Environment:
Python 3.4.4 on Windows 7 6.1.7601 AMD64
Installed Packages:
AnyQt==0.0.8, Bottleneck==1.2.0, Orange3-Educational==0.0.3, Orange3-ImageAnalytics==0.1.5, Orange3==3.4.2, Pillow==4.1.0, PyQt4==4.11.4, chardet==2.3.0, dill==0.2.6, docutils==0.13.1, h2==2.6.2, hpack==3.0.0, hyper==0.7.0, hyperframe==3.2.0, joblib==0.11, keyring==10.3, keyrings.alt==2.0, numpy==1.12.0, olefile==0.44, pip==8.1.2, pygraphviz==1.3rc2, pyqtgraph==0.10.0, pyreadline==2.1, pywin32-ctypes==0.0.1, scikit-learn==0.18.1, scipy==0.16.1, setuptools==18.2, xlrd==1.0.0
Machine ID:
84440847225592
Stack Trace:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 822, in process_signals_for_widget
    handler(*args)
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\widgets\owimageembedding.py", line 114, in set_data
    self._cb_image_attr_changed()
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\widgets\owimageembedding.py", line 123, in _cb_image_attr_changed
    self.commit()
  File "C:\Python34\lib\site-packages\Orange\widgets\gui.py", line 1990, in unconditional_commit
    do_commit()
  File "C:\Python34\lib\site-packages\Orange\widgets\gui.py", line 1998, in do_commit
    commit()
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\widgets\owimageembedding.py", line 141, in commit
    image_processed_callback=lambda: progress.advance()
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\image_embedder.py", line 109, in __call__
    for batch in self._yield_in_batches(file_paths):
  File "C:\Python34\lib\site-packages\orangecontrib\imageanalytics\image_embedder.py", line 137, in _yield_in_batches
    batch = list(islice(gen_, batch_size))
ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.

Local Variables:
{'batch_size': 4294967297,
 'gen_': <generator object <genexpr> at 0x0E7B7120>,
 'list_': array([ 'C:\\Users\\Kamil\\Desktop\\Praca mgr\\images\\Królowa-i-Szekspir-Teatr-Telewizji.jpg',
       'C:\\Users\\Kamil\\Desktop\\Praca mgr\\images\\pobrane.jpg',
       'C:\\Users\\Kamil\\Desktop\\Praca mgr\\images\\w oknie.JPG'], dtype=object),
 'num_yielded': 0,
 'self': <orangecontrib.imageanalytics.image_embedder.ImageEmbedder object at 0x0E795C10>}
```

Regards

**Comment by ajdapretnar** [comment] 2017-05-05 10:25
@inejc Do you know what could be the issue? I couldn't reproduce it on my machine (Win10).

**Comment by inejc** [comment] 2017-05-12 18:27
I wasn't able to reproduce this either. I have added a fallback (default) value for the conflicting setting however and changes are available in version 0.1.6. Any feedback would be greatly appreciated.

**Comment by PrimozGodec** [comment] 2017-11-10 14:06
Anything new on this bug?

**Comment by PrimozGodec** [comment] 2017-11-17 12:58
Closing since no additional informations and cannot reproduce. You are welcome to reopen it with some additional informations.

**Closed by PrimozGodec** 2017-11-17 12:58 UTC
